### ISSUE TITLE
Schema is incompatible with MySQL 5.5 - VARCHAR requires a length

### ISSUE THREAD

**Issue by brycied00d** [errbotio/err-storage-sql#1]
# Versions

errbot 4.0.3
SQLAlchemy 1.0.12
python3-mysqldb 1.3.7
Python 3.4.2
MySQL 5.5.47
# Error

`sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql`
Starting errbot with a fresh, empty MySQL database errors out during table creation.
# Reproduction

Fresh errbot install and err-storage-sql clone according to the README. `config.py` contains:

``` python
BOT_EXTRA_STORAGE_PLUGINS_DIR='/home/brycec/errbot/storage'
STORAGE = 'SQL'
STORAGE_CONFIG = {
  'data_url': 'mysql+mysqldb://errbot:errbot@localhost/errbot',
  }
```

The `errbot` user has been granted `ALL` privileges on the `errbot` database.
# Suggested Fix

This patch specifies fixed column size limits. `767` is MySQL's MyISAM limit for a primary key; `32768` is somewhat arbitrary, hopefully large enough, and will only work on versions > 5.0, prior to which the VARCHAR limit was 255.

``` patch
diff --git a/sql.py b/sql.py
index 02fe801..36a2349 100644
--- a/sql.py
+++ b/sql.py
@@ -89,8 +89,8 @@ class SQLPlugin(StoragePluginBase):

         # Create a table with the given namespace
         table = Table(namespace, self._metadata,
-                Column('key', String(), primary_key=True),
-                Column('value', String()),
+                Column('key', String(767), primary_key=True),
+                Column('value', String(32768)),
                 )

         class NewKV(KV):
```
# Documentation

http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.String.params.length
# Full Backtrace

```
15:18:03 INFO     errbot.err                Config check passed...
15:18:03 INFO     errbot.err                Selected backend 'Text'.
15:18:03 INFO     errbot.err                Checking for '/home/brycec/errbot'...
15:18:04 INFO     errbot.specific_plugin_ma storage search paths {'/home/brycec/errbot/storage/err-storage-sql', '/usr/local/lib/python3.4/dist-packages/errbot/storage'}
15:18:04 INFO     errbot.specific_plugin_ma Found those plugings available:
15:18:04 INFO     errbot.specific_plugin_ma            SQL  (/home/brycec/errbot/storage/err-storage-sql/sql.py)
15:18:04 INFO     errbot.specific_plugin_ma         Memory  (/usr/local/lib/python3.4/dist-packages/errbot/storage/memory.py)
15:18:04 INFO     errbot.specific_plugin_ma          Shelf  (/usr/local/lib/python3.4/dist-packages/errbot/storage/shelf.py)
15:18:04 INFO     errbot.main               Found Storage plugin: 'SQL'
Description: This is the errbot storage plugin for SQL. It is compatible with Firebird, Microsoft SQL Server, MySQL, Oracle, PostgreSQL, SQLite, Sybase, IBM DB2, Amazon Redshift, exasol, Sybase SQL Anywhere, MonetDB.
15:18:04 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/storage/memory.plug'  rejected by strategy 'SpecificBackendLocator'
15:18:04 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/storage/shelf.plug'  rejected by strategy 'SpecificBackendLocator'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2159, in visit_create_table
    and not first_pk)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2190, in visit_create_column
    first_pk=first_pk
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1961, in get_column_specification
    column.type, type_expression=column)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 261, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2591, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2313, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/errbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/errbot/err.py", line 261, in main
    main(backend, logger, config, restore)
  File "/usr/local/lib/python3.4/dist-packages/errbot/main.py", line 134, in main
    bot = setup_bot(bot_class, logger, config, restore)
  File "/usr/local/lib/python3.4/dist-packages/errbot/main.py", line 71, in setup_bot
    plugin_indexes)
  File "/usr/local/lib/python3.4/dist-packages/errbot/repo_manager.py", line 84, in __init__
    self.open_storage(storage_plugin, 'repomgr')
  File "/usr/local/lib/python3.4/dist-packages/errbot/storage/__init__.py", line 34, in open_storage
    self._store = storage_plugin.open(namespace)
  File "/home/brycec/errbot/storage/err-storage-sql/sql.py", line 105, in open
    self._metadata.create_all(self._engine)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
    tables=tables)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 730, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 764, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 962, in _execute_ddl
    compiled = ddl.compile(dialect=dialect)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2170, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2159, in visit_create_table
    and not first_pk)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2190, in visit_create_column
    first_pk=first_pk
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1961, in get_column_specification
    column.type, type_expression=column)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 261, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py", line 2591, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2313, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table 'repomgr', column 'key'): VARCHAR requires a length on dialect mysql
```

**Comment by gbin** [comment]
Thanks for your reports! Sorry it took us a long time to look at them. Question: Can't we use something like class sqlalchemy.dialects.mysql.LONGTEXT or another one available for this ?
http://docs.sqlalchemy.org/en/latest/dialects/mysql.html

**Comment by autoferrit** [comment]
I still get this issue. Is there any new updates on this? I would like to have an sql backend as this is the only option I can find. I am on python 3.5 and mysql 5.7

**Comment by gbin** [comment]
@SkiftCreative does the proposed patch fixes the problem for you ?

**Comment by rchannel** [comment]
Suggested fix worked for me.

**Comment by alvesjc** [comment]
Hi.

I'm using csvkit and I'm stuck in this error.

I can't find sql.py in my python folder to try this fix.

Can someone help with this issue in csvkit?

**Comment by zx1986** [comment]
> Column('value', String(32768)),

sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) 
(1074, "Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead")
